export enum ActionType {
   GET_LOADING_STATE = "GET_LOADING_STATE",
   PRODUCT_LOADING_ERROR = "PRODUCT_LOADING_ERROR",
   GET_PRODCUTS = "GET_PRODCUTS",
   ADD_CART = "ADD_CART",
   REMOVE_CART_ITEM = "REMOVE_CART_ITEM",
   INCREASE_CART_QTY = "INCREASE_CART_QTY",
   DECREASE_CART_QTY = "DECREASE_CART_QTY",
   GET_TOTAL_PRICE = "GET_TOTAL_PRICE",
   GET_PRODUCT_IN_DETAILPAGE_BANNER = "GET_PRODUCT_IN_DETAILPAGE_BANNER",
   GET_FILTERED_PRODUCTS = 'GET_FILTERED_PRODUCTS',
   GET_SEARCH_PRODUCTS = 'GET_SEARCH_PRODUCTS',
   REGISTER_USER = 'REGISTER_USER',
   LOGIN_USER = 'LOGIN_USER',
   CANCEL_REGISTER_FORM = 'CANCEL_REGISTER_FORM'
}
