export enum ActionType {
   GET_PRODCUTS = "GET_PRODCUTS",
   ADD_CART = "ADD_CART",
   REMOVE_CART_ITEM = "REMOVE_CART_ITEM",
   INCREASE_CART_QTY = "INCREASE_CART_QTY",
   DECREASE_CART_QTY = "DECREASE_CART_QTY",
   GET_TOTAL_PRICE = "GET_TOTAL_PRICE",
   GET_PRODUCT_IN_DETAILPAGE_BANNER = "GET_PRODUCT_IN_DETAILPAGE_BANNER",
}
